### ISSUE TITLE
High CPU usage in GetTaggedSqlQuery sql.IndexOf

### ISSUE THREAD

**Issue by marvc1** [VariableNotFound/ef6-tagwith#10]
Thank you for creating this library!

In our live environment, since tagging 2 of our main EF queries we're getting really high CPU usage. Here's a couple of screenshots of the profiling;

![image](https://user-images.githubusercontent.com/2427797/201720933-0e2466b3-d58b-405a-839c-bf8ea36bdbcd.png)

![image](https://user-images.githubusercontent.com/2427797/201726051-991676d4-a791-4ce3-a905-ebcf5ecba3e4.png)

`TagMode = TagMode.Infix`

It appears it is the performance of string.indexOf here https://github.com/VariableNotFound/ef6-tagwith/blob/77d3930c44051ce65bd921f327da9d9e4a596821/src/EF6.TagWith/SqlServerTagger.cs#L10

Here's a stackoverflow talking about [string.IndexOf performance](https://stackoverflow.com/questions/7935945/string-indexof-performance)  -https://stackoverflow.com/questions/7935945/string-indexof-performance

**Comment by jmaguilar** [comment]
Hello, 

Could please you provide a sample SQL where this is happening? It doesn't matter if you change some table/column names to don't undisclose details, it is just for making some benchmarks using a real scenario.

Thank you!

**Comment by marvc1** [comment]
Hey @jmaguilar, I've taken a look at one of these SQL queries in SQL profiler, and then opened it in Notepad.

It's 327 lines long, and 19,426 characters. So it's big, but there is bigger in an application like ours. I can't share it as pretty much every table and column name discloses some data.

Does that help?

**Comment by jmaguilar** [comment]
Hi, @marvc1 

Yeah, at least it can give an idea about the size of the string (that is in fact a big string). 

Obviously, it takes some time to search a large string like this, specially if the searched text is not found because you need to iterate through all its contents, and this takes CPU time. The link that you suggested talks about the benefits or performing an ordinal comparison, but we are already using StringComparison.Ordinal, so I'm not sure if we'll be able to improve this.

I'm a bit busy these weeks but I'll try to investigate if we could apply some kind of optimization at this point.

Of course, you are welcome to help trying to figure out a good solution for this issue. You could do it simply downloading the project source code and adding it to your solution, and then add references to it from the your EF projects instead of using the NuGet package. I'll be glad to receive your ideas or suggestions :)

Thanks!

**Comment by jmaguilar** [comment]
Hi!

I was able to take a quick look at this.

I don't think we can do much to improve performance at that point. The way this component works requires to search the tag marker in the SQL string and, as far as I know, there is not a fastest way to do it. Inevitably, `IndexOf()` will consume time and resources if the string is long.

Therefore. if this CPU consumption is critical for you, my recommendation is to uninstall the component from your project.

Anyway, I'm open to hear your ideas or suggestions about how we could improve it.

Thanks!

**Comment by marvc1** [comment]
Forgive me, I don't have a full understanding of the source code, and the string indexing. But how about this as a starting idea;

On [line 10](https://github.com/VariableNotFound/ef6-tagwith/blob/77d3930c44051ce65bd921f327da9d9e4a596821/src/EF6.TagWith/SqlServerTagger.cs#L10) it's looking for the tag.

Could this index search exit as soon as it sees the characters "Select" + 10 chars.  

I.e.

1. loop through the string characters one by one
2. once "select" matched, go a maximum of X characters more
3. if no match, then exit.

This leads me to a few questions;

- Can you think of any obvious edge cases where that wouldn't work?
- How would one go about perf testing that? (i.e. is there an existing way this could be tested/benchmarked within the code base)

**Comment by jmaguilar** [comment]
Hello,

It's a bit more complicated than that. When the query is defined via LINQ, the "marker" indicating that we must tag the query (which is in fact a special predicate) is included in the WHERE section. For this reason, we are forced to search almost in the whole string.

About perf testing, you could do it with [BenchmarkDotnet](https://benchmarkdotnet.org/). Using this tool, you can test easily the method `GetTaggedSqlQuery()` because it doesn't depends on anything,  just need a SQL string.

Best,
JM
